import {
  spfOne,
  spfTwo,
  spfThree,
  spfFour,
  bestSellerOne,
  bestSellerTwo,
  bestSellerThree,
  bestSellerFour,
  newArrOne,
  newArrTwo,
  newArrThree,
  newArrFour,
} from "../assets/images/index";

// =================== NavBarList Start here ====================
export const navBarList = [
  {
    _id: 1001,
    title: "Home",
    link: "/",
  },
  {
    _id: 1002,
    title: "Shop",
    link: "/shop",
  },
  {
    _id: 1003,
    title: "About",
    link: "/about",
  },
  {
    _id: 1004,
    title: "Contact",
    link: "contact",
  },
  {
    _id: 1005,
    title: "Journal",
    link: "/journal",
  },
];
// =================== NavBarList End here ======================
// =================== Special Offer data Start here ============
export const SplOfferData = [
 {
  _id: "201",
  img: spfOne,
  productName: "Mũ lưỡi trai cho bé trai",
  price: "35.00",
  color: "Đen và trắng",
  badge: true,
  des: "Chiếc mũ lưỡi trai phong cách, phù hợp cho bé trai năng động. Chất liệu cao cấp, thoáng khí, mang đến sự thoải mái tối đa.",
},
{
  _id: "202",
  img: newArrFour,
  productName: "Bàn trà",
  price: "180.00",
  color: "Xám",
  badge: true,
  des: "Bàn trà hiện đại với thiết kế tinh tế, phù hợp với mọi không gian sống. Được làm từ vật liệu chất lượng cao, bền đẹp theo thời gian.",
},
{
  _id: "203",
  img: spfThree,
  productName: "Tai nghe",
  price: "25.00",
  color: "Nhiều màu",
  badge: true,
  des: "Tai nghe âm thanh rõ nét, thiết kế nhẹ nhàng, giúp bạn tận hưởng âm nhạc mọi lúc, mọi nơi.",
},
{
  _id: "204",
  img: spfFour,
  productName: "Kính râm",
  price: "220.00",
  color: "Đen",
  badge: true,
  des: "Kính râm thời trang, bảo vệ mắt khỏi tia UV và mang lại vẻ ngoài sành điệu. Phù hợp cho mọi chuyến đi.",
},
]
// =================== Special Offer data End here ==============

// =================== PaginationItems Start here ===============

export const paginationItems = [
  {
  _id: 1001,
  img: spfOne,
  productName: "Mũ lưỡi trai cho bé trai",
  price: "35.00",
  color: "Trắng và đen",
  badge: true,
  des: "Mũ lưỡi trai phong cách, phù hợp cho bé trai năng động. Chất liệu cao cấp, thoáng khí, tạo sự thoải mái khi đội.",
},
{
  _id: 1002,
  img: spfTwo,
  productName: "Bàn trà",
  price: "180.00",
  color: "Xám",
  badge: true,
  des: "Bàn trà hiện đại với thiết kế tinh tế, phù hợp với mọi không gian sống. Được làm từ vật liệu chất lượng cao, bền đẹp theo thời gian.",
},
{
  _id: 1003,
  img: spfThree,
  productName: "Tai nghe",
  price: "25.00",
  color: "Nhiều màu",
  badge: true,
  des: "Tai nghe âm thanh chất lượng cao, thiết kế nhỏ gọn, giúp bạn thưởng thức âm nhạc ở mọi nơi.",
},
{
  _id: 1004,
  img: spfFour,
  productName: "Kính râm",
  price: "220.00",
  color: "Đen",
  badge: true,
  des: "Kính râm thời trang, bảo vệ mắt khỏi tia UV và tạo vẻ ngoài sành điệu. Phù hợp cho mọi chuyến đi.",
},
{
  _id: 1005,
  img: bestSellerOne,
  productName: "Bình hoa",
  price: "35.00",
  color: "Trắng và đen",
  badge: true,
  des: "Bình hoa tinh tế, làm nổi bật không gian sống với thiết kế hiện đại và thanh lịch.",
},
{
  _id: 1006,
  img: bestSellerTwo,
  productName: "Ba lô mới",
  price: "180.00",
  color: "Xám",
  badge: false,
  des: "Ba lô thời trang, thiết kế tiện lợi và bền bỉ, lý tưởng cho việc đi học hoặc đi chơi.",
},
{
  _id: 1007,
  img: bestSellerThree,
  productName: "Dụng cụ gia đình",
  price: "25.00",
  color: "Nhiều màu",
  badge: true,
  des: "Bộ dụng cụ gia đình tiện dụng, hỗ trợ các công việc hàng ngày một cách hiệu quả.",
},
{
  _id: 1008,
  img: bestSellerFour,
  productName: "Túi du lịch",
  price: "220.00",
  color: "Đen",
  badge: false,
  des: "Túi du lịch rộng rãi và chắc chắn, giúp bạn mang theo đầy đủ hành lý cho những chuyến đi dài ngày.",
},
{
  _id: 1009,
  img: newArrOne,
  productName: "Đồng hồ để bàn tròn",
  price: "44.00",
  color: "Đen",
  badge: true,
  des: "Đồng hồ để bàn với thiết kế tròn hiện đại, làm đẹp không gian sống và dễ dàng theo dõi thời gian.",
},
{
  _id: 1010,
  img: newArrTwo,
  productName: "Đồng hồ thông minh",
  price: "250.00",
  color: "Đen",
  badge: true,
  des: "Đồng hồ thông minh với nhiều tính năng tiện ích, hỗ trợ theo dõi sức khỏe và kết nối thông minh.",
},
{
  _id: 1011,
  img: newArrThree,
  productName: "Giỏ đựng đồ",
  price: "80.00",
  color: "Nhiều màu",
  badge: true,
  des: "Giỏ đựng đồ tiện lợi và chắc chắn, giúp bạn tổ chức không gian sống gọn gàng và ngăn nắp.",
},
{
  _id: 1012,
  img: newArrFour,
  productName: "Đồ chơi vui nhộn cho bé",
  price: "60.00",
  color: "Nhiều màu",
  badge: false,
  des: "Đồ chơi sáng tạo và vui nhộn, giúp bé phát triển tư duy và khả năng sáng tạo.",
},
{
  _id: 1013,
  img: newArrTwo,
  productName: "Đồ chơi vui nhộn cho bé",
  price: "60.00",
  color: "Nhiều màu",
  badge: false,
  des: "Đồ chơi sáng tạo và vui nhộn, giúp bé phát triển tư duy và khả năng sáng tạo.",
},
{
  _id: 1014,
  img: newArrTwo,
  productName: "Đồng hồ thông minh",
  price: "250.00",
  color: "Đen",
  badge: true,
  des: "Đồng hồ thông minh với nhiều tính năng tiện ích, hỗ trợ theo dõi sức khỏe và kết nối thông minh.",
},
{
  _id: 1015,
  img: newArrFour,
  productName: "Đồ chơi vui nhộn cho bé",
  price: "60.00",
  color: "Nhiều màu",
  badge: false,
  des: "Đồ chơi sáng tạo và vui nhộn, giúp bé phát triển tư duy và khả năng sáng tạo.",
},
{
  _id: 1016,
  img: newArrTwo,
  productName: "Đồng hồ thông minh",
  price: "250.00",
  color: "Đen",
  badge: true,
  des: "Đồng hồ thông minh với nhiều tính năng tiện ích, hỗ trợ theo dõi sức khỏe và kết nối thông minh.",
},
{
  _id: 1017,
  img: bestSellerFour,
  productName: "Túi du lịch",
  price: "220.00",
  color: "Đen",
  badge: false,
  des: "Túi du lịch rộng rãi và chắc chắn, giúp bạn mang theo đầy đủ hành lý cho những chuyến đi dài ngày.",
},
{
  _id: 1018,
  img: newArrOne,
  productName: "Đồng hồ để bàn tròn",
  price: "44.00",
  color: "Đen",
  badge: true,
  des: "Đồng hồ để bàn với thiết kế tròn hiện đại, làm đẹp không gian sống và dễ dàng theo dõi thời gian.",
},
{
  _id: 1019,
  img: newArrTwo,
  productName: "Đồng hồ thông minh",
  price: "250.00",
  color: "Đen",
  badge: true,
  des: "Đồng hồ thông minh với nhiều tính năng tiện ích, hỗ trợ theo dõi sức khỏe và kết nối thông minh.",
},
{
  _id: 1020,
  img: newArrThree,
  productName: "Giỏ đựng đồ",
  price: "80.00",
  color: "Nhiều màu",
  badge: true,
  des: "Giỏ đựng đồ tiện lợi và chắc chắn, giúp bạn tổ chức không gian sống gọn gàng và ngăn nắp.",
},

 {
  _id: 1021,
  img: spfThree,
  productName: "Tai nghe",
  price: "25.00",
  color: "Nhiều màu",
  badge: true,
  des: "Tai nghe âm thanh chất lượng cao, thiết kế nhỏ gọn, giúp bạn thưởng thức âm nhạc ở mọi nơi.",
},
{
  _id: 1022,
  img: spfFour,
  productName: "Kính râm",
  price: "220.00",
  color: "Đen",
  badge: true,
  des: "Kính râm thời trang, bảo vệ mắt khỏi tia UV và tạo vẻ ngoài sành điệu. Phù hợp cho mọi chuyến đi.",
},
{
  _id: 1023,
  img: bestSellerOne,
  productName: "Bình hoa",
  price: "35.00",
  color: "Trắng và đen",
  badge: true,
  des: "Bình hoa tinh tế, làm nổi bật không gian sống với thiết kế hiện đại và thanh lịch.",
},
{
  _id: 1024,
  img: spfOne,
  productName: "Mũ lưỡi trai cho bé trai",
  price: "35.00",
  color: "Trắng và đen",
  badge: true,
  des: "Mũ lưỡi trai phong cách, phù hợp cho bé trai năng động. Chất liệu cao cấp, thoáng khí, tạo sự thoải mái khi đội.",
},
{
  _id: 1025,
  img: spfTwo,
  productName: "Bàn trà",
  price: "180.00",
  color: "Xám",
  badge: true,
  des: "Bàn trà hiện đại với thiết kế tinh tế, phù hợp với mọi không gian sống. Được làm từ vật liệu chất lượng cao, bền đẹp theo thời gian.",
},
{
  _id: 1026,
  img: spfThree,
  productName: "Tai nghe",
  price: "25.00",
  color: "Nhiều màu",
  badge: true,
  des: "Tai nghe âm thanh chất lượng cao, thiết kế nhỏ gọn, giúp bạn thưởng thức âm nhạc ở mọi nơi.",
},
{
  _id: 1027,
  img: spfFour,
  productName: "Kính râm",
  price: "220.00",
  color: "Đen",
  badge: true,
  des: "Kính râm thời trang, bảo vệ mắt khỏi tia UV và tạo vẻ ngoài sành điệu. Phù hợp cho mọi chuyến đi.",
},
{
  _id: 1028,
  img: bestSellerOne,
  productName: "Bình hoa",
  price: "35.00",
  color: "Trắng và đen",
  badge: true,
  des: "Bình hoa tinh tế, làm nổi bật không gian sống với thiết kế hiện đại và thanh lịch.",
},
{
  _id: 1029,
  img: bestSellerTwo,
  productName: "Ba lô mới",
  price: "180.00",
  color: "Xám",
  badge: false,
  des: "Ba lô thời trang, thiết kế tiện lợi và bền bỉ, lý tưởng cho việc đi học hoặc đi chơi.",
},
{
  _id: 1030,
  img: bestSellerThree,
  productName: "Dụng cụ gia đình",
  price: "25.00",
  color: "Nhiều màu",
  badge: true,
  des: "Bộ dụng cụ gia đình tiện dụng, hỗ trợ các công việc hàng ngày một cách hiệu quả.",
},
{
  _id: 1031,
  img: bestSellerFour,
  productName: "Túi du lịch",
  price: "220.00",
  color: "Đen",
  badge: false,
  des: "Túi du lịch rộng rãi và chắc chắn, giúp bạn mang theo đầy đủ hành lý cho những chuyến đi dài ngày.",
},
{
  _id: 1032,
  img: newArrOne,
  productName: "Đồng hồ để bàn tròn",
  price: "44.00",
  color: "Đen",
  badge: true,
  des: "Đồng hồ để bàn với thiết kế tròn hiện đại, làm đẹp không gian sống và dễ dàng theo dõi thời gian.",
},
{
  _id: 1033,
  img: newArrTwo,
  productName: "Đồng hồ thông minh",
  price: "250.00",
  color: "Đen",
  badge: true,
  des: "Đồng hồ thông minh với nhiều tính năng tiện ích, hỗ trợ theo dõi sức khỏe và kết nối thông minh.",
},
{
  _id: 1034,
  img: newArrThree,
  productName: "Giỏ đựng đồ",
  price: "80.00",
  color: "Nhiều màu",
  badge: true,
  des: "Giỏ đựng đồ tiện lợi và chắc chắn, giúp bạn tổ chức không gian sống gọn gàng và ngăn nắp.",
},
{
  _id: 1035,
  img: newArrFour,
  productName: "Đồ chơi vui nhộn cho bé",
  price: "60.00",
  color: "Nhiều màu",
  badge: false,
  des: "Đồ chơi sáng tạo và vui nhộn, giúp bé phát triển tư duy và khả năng sáng tạo.",
},
{
  _id: 1036,
  img: newArrTwo,
  productName: "Đồ chơi vui nhộn cho bé",
  price: "60.00",
  color: "Nhiều màu",
  badge: false,
  des: "Đồ chơi sáng tạo và vui nhộn, giúp bé phát triển tư duy và khả năng sáng tạo.",
},
{
  _id: 1037,
  img: newArrFour,
  productName: "Đồ chơi vui nhộn cho bé",
  price: "60.00",
  color: "Nhiều màu",
  badge: false,
  des: "Đồ chơi sáng tạo và vui nhộn, giúp bé phát triển tư duy và khả năng sáng tạo.",
},
{
  _id: 1038,
  img: newArrTwo,
  productName: "Đồng hồ thông minh",
  price: "250.00",
  color: "Đen",
  badge: true,
  des: "Đồng hồ thông minh với nhiều tính năng tiện ích, hỗ trợ theo dõi sức khỏe và kết nối thông minh.",
},
{
  _id: 1039,
  img: bestSellerFour,
  productName: "Túi du lịch",
  price: "220.00",
  color: "Đen",
  badge: false,
  des: "Túi du lịch rộng rãi và chắc chắn, giúp bạn mang theo đầy đủ hành lý cho những chuyến đi dài ngày.",
},
{
  _id: 1040,
  img: newArrOne,
  productName: "Đồng hồ để bàn tròn",
  price: "44.00",
  color: "Đen",
  badge: true,
  des: "Đồng hồ để bàn với thiết kế tròn hiện đại, làm đẹp không gian sống và dễ dàng theo dõi thời gian.",
},

  {
  _id: 1041,
  img: newArrTwo,
  productName: "Đồng hồ thông minh",
  price: "250.00",
  color: "Đen",
  badge: true,
  des: "Đồng hồ thông minh với nhiều tính năng tiện ích, hỗ trợ theo dõi sức khỏe và kết nối thông minh.",
},
{
  _id: 1042,
  img: newArrThree,
  productName: "Giỏ đựng đồ",
  price: "80.00",
  color: "Nhiều màu",
  badge: true,
  des: "Giỏ đựng đồ tiện lợi và chắc chắn, giúp bạn tổ chức không gian sống gọn gàng và ngăn nắp.",
},
{
  _id: 1043,
  img: spfThree,
  productName: "Tai nghe",
  price: "25.00",
  color: "Nhiều màu",
  badge: true,
  des: "Tai nghe âm thanh chất lượng cao, thiết kế nhỏ gọn, giúp bạn thưởng thức âm nhạc ở mọi nơi.",
},
{
  _id: 1044,
  img: spfFour,
  productName: "Kính râm",
  price: "220.00",
  color: "Đen",
  badge: true,
  des: "Kính râm thời trang, bảo vệ mắt khỏi tia UV và tạo vẻ ngoài sành điệu. Phù hợp cho mọi chuyến đi.",
},
{
  _id: 1045,
  img: bestSellerOne,
  productName: "Bình hoa",
  price: "35.00",
  color: "Trắng và đen",
  badge: true,
  des: "Bình hoa tinh tế, làm nổi bật không gian sống với thiết kế hiện đại và thanh lịch.",
},
{
  _id: 1046,
  img: spfOne,
  productName: "Mũ lưỡi trai cho bé trai",
  price: "35.00",
  color: "Trắng và đen",
  badge: true,
  des: "Mũ lưỡi trai phong cách, phù hợp cho bé trai năng động. Chất liệu cao cấp, thoáng khí, tạo sự thoải mái khi đội.",
},

];
// =================== PaginationItems End here =================
